#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

if find "$repo_root" \
    \( -path "$repo_root/.git" -o -path "$repo_root/node_modules" -o -path "$repo_root/dist" \) -prune \
    -o -type l -print -quit | grep -q .; then
    printf 'Symbolic links are not permitted.\n' >&2
    exit 1
fi

forbidden_pattern='(chat''gpt|open''ai|clau''de|co''pilot|generated by a''i|BEGIN (RSA |OPENSSH )?PRIVATE KEY)'

if rg -n -i --hidden \
    --glob '!.git/**' \
    --glob '!node_modules/**' \
    --glob '!dist/**' \
    --glob '!package-lock.json' \
    --glob '!tests/repository-hygiene.test.sh' \
    "$forbidden_pattern" \
    "$repo_root"; then
    printf 'Forbidden private, credential, or authorship text found.\n' >&2
    exit 1
fi

if rg -n --hidden \
    --glob '!.git/**' \
    --glob '!node_modules/**' \
    --glob '!dist/**' \
    '(rpcpassword|RPC_PASSWORD|RPC_CREDENTIALS)=[^$<{[:space:]][^[:space:]]*' \
    "$repo_root"; then
    printf 'A committed RPC credential value was found.\n' >&2
    exit 1
fi

printf 'Repository hygiene checks passed.\n'
